version: '3.3'
services:
  db:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: Nastya123
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3307:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_SCRIPTS_DIR}:/docker-entrypoint-initdb.d/
